//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NajamAutaEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozila()
        {
            this.Rezervacije = new HashSet<Rezervacije>();
        }
    
        public int IdVozila { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int Godiste { get; set; }
        public string Gorivo { get; set; }
        public string Registracija { get; set; }
        public bool Kuka { get; set; }
        public int Lokacija { get; set; }
    
        public virtual Lokacije Lokacije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacije> Rezervacije { get; set; }
    }
}
